### PR TITLE
Draft example snakefiles.

### PR DESCRIPTION
**Pull request by reid-a**
Hopefully the names are reasonably self-explanatory for now. Once they're in the lesson context, it will all make more sense.

### CODE REVIEW

**Comment by tobyhodges** [comment]
These are all surprisingly (and pleasingly) short. However, reading them like this I realise that (apart from one, relatively contrived example) they are single-rule files. Given the title of the lesson, should we be aiming for a final product that could more reasonably be described as a workflow? Something that answers the question "How should I design and execute a multi-rule workflow where some rules should run on the cluster?"

**Comment by reid-a** [comment]
We are aiming for such a final product, but it's not reflected in the current PR.

There's at least one more Snakefile that iterates over the various widths to execute the Amdahl's law scaling study, and possibly another one that aggregates the results in order to produce a plot. (There's an open question about how much attention plotting should have, but that's secondary to this PR.) Neither of those snakefiles exists yet.

We do know how to iterate, I have this snakefile that uses wildcard magic to generate three files, and a final rule that won't fire until all three files exist. The deficiencies are, of course, that it's highly contrived, doesn't actually use the inputs to generate the final output, and doesn't run on the cluster. The merits are that it does, in fact, work.
```
#
# Iterative example.
#
NAMES=['one','two','three']
#
rule done:
  input: expand('{name}.out',name=NAMES)
  output: 'done.out'
  shell: 'echo "Done!" > done.out'
rule iterate:
  input: 
  output: '{sample}.out' 
  shell: 'echo {output} > {output}'

```

**Comment by tobyhodges** [comment]
> The merits are that it does, in fact, work.

A merit that should not be undervalued, but often is 😆 

Ok, great stuff: my misconception was that this was the full set.

**Review by tkphd — APPROVED** [review]
Nice start, thank you!

**Pull request merged**
