### PR TITLE
Completely update the lesson

### PR DESCRIPTION
**Pull request by ocaisa**
This update is completely disruptive, it's basically an entirely new lesson written for Snakemake 8.x

You can find the rendered version at  https://ocaisa.github.io/hpc-workflows/01-introduction.html

There are still a few holes:

- [ ] Setup instructions are not complete
- [x] No credit given to the origin lessons for the content
- [ ] Questions, objectives and keypoints need work
- [ ] Timings need work (though I did manage to fit the lesson in a 4 hour window)
- [ ] Requires some learner profiles as motivation

### CODE REVIEW

**Comment by tkphd** [comment]
I changed this to a draft, so that it does not get merged until we address the attribution gap for resources we borrowed material from. Otherwise, we're in violation of the authors' copy-rights.

**Comment by tobyhodges** [comment]
Regarding attribution of other content, a heads-up that the lesson infrastructure will soon support Citation File Format. In addition to adding attribution to the lesson site itself, you can [use the `references` section of a CFF file](https://github.com/citation-file-format/citation-file-format/blob/main/schema-guide.md#referencing-other-work) to cite other works on which your lesson content is based/inspired by.

**Comment by ocaisa** [comment]
> I changed this to a draft, so that it does not get merged until we address the attribution gap for resources we borrowed material from. Otherwise, we're in violation of the authors' copy-rights.

@tkphd I've added a `CITATION.cff` which includes references to the main lessons from which I've incorporated content.

**Review by tkphd — APPROVED** [review]
Looks good! Thank you for all the work, @ocaisa!

**Pull request merged**
